---
# How-to:
# ansible-playbook -vv playbooks/pb_control_worker_nodes.yaml --ask-vault-pass -i 127.0.0.1, -c local
- hosts: all
  gather_facts: false
  vars:
    nodes:
      - control0
      - control1
      - control2
      - worker0
      - worker1
      - worker2
  tasks:
  # Create a vault with `ovirt_password` variable which store your
  # oVirt/RHV user's password, and include that yaml file with variable:
  - ansible.builtin.include_vars: ../files/ovirt_password.yml
  - name: "Obtain SSO token with using username/password credentials"
    redhat.rhv.ovirt_auth:
      url: https://rhel88.ocp4.keights.org/ovirt-engine/api
      username: admin@internal
      insecure: yes
      state: present
      password: "{{ ovirt_password }}"
  # Creates a new server rhel7 Virtual Machine from Blank template
  # on brq01 cluster with 2GiB memory and 2 vcpu cores/sockets
  # and attach bootable disk with name rhel7_disk and attach virtio NIC
  - redhat.rhv.ovirt_vm:
      auth:
        url: https://rhel88.ocp4.keights.org/ovirt-engine/api
        token: "{{ ovirt_auth.token }}"
        username: admin@internal
        insecure: yes
      state: present
      cluster: rhev0-Local
      storage_domain: rhev0-Local
      name: "{{ item }}"
      memory: 16GiB
      memory_guaranteed: 16GiB
      memory_max: 16GiB
      cpu_cores: 4
      cpu_sockets: 1
      type: server
      operating_system: rhcos_x64
      nics:
        - name: nic1
          profile_name: openshift4
    with_items:
      - "{{ nodes }}"
    notify:
    - "revoke_the_SSO_token"
    - redhat.rhv.ovirt_disk:
      auth:
        url: https://rhel88.ocp4.keights.org/ovirt-engine/api
        token: "{{ ovirt_auth.token }}"
        username: admin@internal
        insecure: yes
      name: "{{ item }}_disk"
      vm_name: "{{ item }}"
      size: 120GiB
      format: cow
      interface: virtio
      storage_domain: rhev0-Local
    with_items:
      - "{{ nodes }}"
    notify:
    - "revoke_the_SSO_token"
  handlers:
  - name: "revoke_the_SSO_token"
    redhat.rhv.ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
