---
# How-to:
# ansible-playbook -vv playbooks/pb_host_info.yaml --ask-vault-pass -i 127.0.0.1, -c local
- hosts: all
  gather_facts: false
  tasks:
  - block:
      # Create a vault with `ovirt_password` variable which store your
      # oVirt/RHV user's password, and include that yaml file with variable:
      - ansible.builtin.include_vars: ../files/ovirt_password.yml
      - name: "Obtain SSO token with using username/password credentials"
        redhat.rhv.ovirt_auth:
          url: https://rhel88.ocp4.keights.org/ovirt-engine/api
          username: admin@internal
          insecure: yes
          state: present
          password: "{{ ovirt_password }}"
      # Previous task generated I(ovirt_auth) fact, which you can later use
      # in different modules as follows:
      # Gather information about host and belongs to data center Default
      - redhat.rhv.ovirt_host_info:
          pattern: name=rhev0 and datacenter=rhev0-local
          auth:
            url: https://rhel88.ocp4.keights.org/ovirt-engine/api
            token: "{{ ovirt_auth.token }}"
            username: admin@internal
            insecure: yes
        register: result
      - ansible.builtin.debug:
          msg: "{{ result.ovirt_hosts }}"
    always:
      - name: "Always revoke the SSO token"
        redhat.rhv.ovirt_auth:
          state: absent
          ovirt_auth: "{{ ovirt_auth }}"
